@startuml "challenge-flow"
actor UserAgent
entity RelyingParty
entity OAuthServer

RelyingParty -> OAuthServer: Request ephemeral challenge
OAuthServer --> RelyingParty : Ephemeral challenge response

RelyingParty -> UserAgent: Present ephemeral challenge

loop await UserAgent response
	RelyingParty -> OAuthServer: Request token
	OAuthServer --> RelyingParty: "authorization_pending" response
end
alt UserAgent response
    UserAgent -> OAuthServer : Submit Challenge Response
end

RelyingParty -> OAuthServer: Request token
OAuthServer --> RelyingParty: "token" response
@enduml