@startuml

actor Alice as A #white
actor Bob as B #white

'1. Connection Offer

rnote over A #white
{
    "id": offer_nonce
    "type": connection_offer
    "content": {
        "endpoint": {
            "did": A.endpoint.did
             — or —
            "uri": A.endpoint.uri
            "verkey": A.endpoint.vk
        }
    }
}
end note

A -> B: **1.** A makes a **Connection Offer**, in\nperson or securely over internet
||35||


'2. Connection Request
rnote over B #white
{
    "id": offer_nonce (optional)
    "type": connection_request
    "content": {
        "did": B.did@B:A
        "verkey": B.vk@B:A
        "endpoint": B.endpoint
    }
}
end note

B -> A: **2.** B sends **Connection Request** message
||35||


'3. Connection Response
rnote over A #white
{
    "to": A.did@B:A,
    "type": connection_response,
    "content": {
            "did": A.did@A:B,
            "verkey": A.vk@A:B
    }
}
end note

A -> B: **3.** A sends **Connection Response** message
||35||


'4. Bob's Acknowledgement
rnote over B #white
{
    "to": A.did@A:B
    "type": message_acknowledgement
    "message": "success"
}
end note

B -> A: **4.** B sends **Connection Acknowledgement** 
||35||


'5. Alice's Acknowledgement
rnote over A #white
{
    "id": B.did@B:A
    "type": message_acknowledgement
    "message": "success"
}
end note

A -> B: **5.** A sends **Connection Acknowledgement** 
||35||


A <-> B: A & B can now send auth-encrypted messages

@enduml