@startuml
actor Alice #white
actor Bob #white

Alice --> Bob : invite
rnote left #white
    * endpoint information
       endpoint did
           or
       endpoint uri
       endpoint key
    * connection key (one time use)
end note

Bob --> Alice: request
rnote right #white
anon_crypted(endpoint_key, {
    @type: "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/routing/1.0/forward_to_key",
    key: connection key (one time use),
    content: {
        @type: "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/request",
        key: connection key (one time use),
        content: auth_crypted(connection key, {
            did: // did on a public ledger
                or
            did_doc:
        })
    }
})
end note
Alice --> Bob: response
rnote left #white
anon_crypted(endpoint_key, {
    @type: "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/routing/1.0/forward",
    to: "ABC",
    content: {
        @type: "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/response",
        to: "did:sov:ABC",
        content: auth_crypted("123", {
            did: // did on a public ledger
                or
            did_doc:
        })
    }
})
end note

Bob --> Alice: future messages
rnote right #white
anon_crypted(endpoint_key, {
    @type: "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/routing/1.0/forward",
    to: "ABC",
    content: {
        @type: ,
        from: "did:sov:ABC",
        content: auth_crypted( , )
    }
})
end note
@enduml